// THIS FILE IS AUTOGENERATED
// DO NOT EDIT THIS FILE!

import * as lunr from "../../../lunr.js";
import "@algolia/autocomplete-theme-classic";
import "./index.css";
export const tokenize = (input) => lunr.tokenizer(input)
  .map(token => token.str);
export const mylunr = lunr;
